#!/bin/bash

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/tidal/
NAME=`hostname`_`ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`

/usr/bin/tcon \
--netif-for-deviceid eth0 \
-f $NAME \
--codec-mpegh true \
--codec-mqa true \
--model-name "OEM" \
--disable-app-security false \
--disable-web-security true \
--enable-mqa-passthrough true \
--log-level 0 \
--tc-certificate-path "/etc/ssl/private/tcon.crt" \
> /dev/null 2>&1 & 


