#!/bin/sh

case "$1" in
    start)
    printf "Starting Scream: "

    i=1
    while [ $i -lt 300 ]
    do
	echo "Number: $i"
        i=$((i+1))
        network=`route |grep UG`
        if [[ -n "$network"  ]]; then
        break
    fi
    sleep 1
    done
    sleep 0.5

nice -n -15 /usr/sbin/scream  > /dev/null 2>&1 &
	;;
    stop)
    killall scream
    ;;
    *)
	exit 1
esac

