#!/bin/sh

case "$1" in
  start)
    printf "Starting Spotify: "
    
    i=1
    while [ $i -lt 300 ]
	do
	echo "Number: $i"
	i=$((i+1))
	network=`route |grep UG`
	if [[ -n "$network"  ]]; then
	break
	fi
	sleep 1
    done

    NAME=`hostname`_`ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`
#    nice -n -15 /sbin/spotifyd --no-audio-cache --no-daemon --cache-path /tmp --bitrate 320 -d $NAME > /dev/null 2>&1 &
#    nice -n -15 /sbin/librespot --cache /tmp --cache-size-limit 100M --bitrate 320 --name $NAME > /dev/null 2>&1 &
    nice -n -15 /sbin/spotifyd --no-audio-cache --no-daemon --cache-path /tmp --bitrate 320 -d $NAME > /dev/null 2>&1 &
#    nice -n -15 /sbin/librespot --cache /tmp --cache-size-limit 100M --bitrate 320 --name librespot_$NAME  --mixer softvol --volume-ctrl fixed --initial-volume 100 > /dev/null 2>&1 &

    ;;
    stop)
    killall spotifyd
    ;;
      *)
        exit 1
esac
