#!/bin/sh

NAME=`hostname`_`ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`
OPTIONS="-C 5 -M $NAME"

case "$1" in
    start)

i=1
    while [ $i -lt 300 ]
    do
    echo "Number: $i"
    i=$((i+1))
    network=`route |grep UG`
    if [[ -n "$network"  ]]; then
    break
    fi
    sleep 1
done
        printf "Starting Squeezelite: "
        start-stop-daemon --start --quiet --background --exec nice -n -15 /usr/bin/squeezelite -- $OPTIONS
                ;;
    stop)
    killall squeezelite
    ;;
        *)
                exit 1
esac
